run:
  timeout: 3m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - dupImport
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/alarm-agent
  
  golint:
    min-confidence: 0.8
  
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  
  govet:
    check-shadowing: true
  
  lll:
    line-length: 120
  
  misspell:
    locale: US
  
  nakedret:
    max-func-lines: 30
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  
  unparam:
    check-exported: false
  
  unused:
    check-exported: false
  
  whitespace:
    multi-if: false
    multi-func: false

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  
  disable:
    - funlen
    - gochecknoglobals
    - gocognit
    - gocyclo
    - godot
    - godox
    - goerr113
    - interfacer
    - maligned
    - nestif
    - prealloc
    - scopelint
    - testpackage
    - wsl

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gomnd
        - lll
    
    # Exclude known linters from partially hard-to-fix issues
    - linters:
        - gosec
      text: "G401|G501" # Weak cryptographic primitive
    
    # Exclude shadow checking on err variables
    - linters:
        - govet
      text: 'shadow: declaration of "(err|ctx)"'
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false